version: '3'

services:
  reverse-proxy:
    image: nginx:1.25.0
    container_name: reverse-proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  vue-2:
    image: vue-2
    container_name: vue-2
    build:
      context: ./vue-2

  vue-3:
    image: vue-3
    container_name: vue-3
    build:
      context: ./vue-3
